server:
  port: 8083

spring:
  application:
    name: NotificationsMicroservice

  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true