server:
  port: 8081

spring:
  application:
    name: BikesMicroservice

  datasource:
    url: jdbc:postgresql://localhost:5432/bike_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true