server:
  port: 8081

spring:
  application:
    name: BikesMicroservice

  datasource:
    url: jdbc:postgresql://localhost:5432/bike_service
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true