server:
  port: 8084

spring:
  application:
    name: PaymentsMicroservice

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true